; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:door]
platform = espressif32
board = esp32dev
framework = arduino
build_flags =
  -DDEVICE_TYPE_DOOR
  -DUNLOCK_MS=800
monitor_speed = 115200

[env:elevator]
platform = espressif32
board = esp32dev
framework = arduino
build_flags =
  -DDEVICE_TYPE_ELEVATOR
  -DUNLOCK_MS=10000
monitor_speed = 115200




lib_deps =
  bblanchon/ArduinoJson
  https://github.com/monkeyboard/Wiegand-Protocol-Library-for-Arduino.git
