"""init

Revision ID: 3764a5d5e161
Revises: c4fc0175b619
Create Date: 2026-01-28 16:51:54.557718

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3764a5d5e161'
down_revision = 'c4fc0175b619'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
