"""add floor, flat_number, tenant_name

Revision ID: c4fc0175b619
Revises: 3b9913996e06
Create Date: 2026-01-28 16:46:45.057051

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c4fc0175b619'
down_revision = '3b9913996e06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flats', sa.Column('floor', sa.Integer(), nullable=False))
    op.add_column('flats', sa.Column('number', sa.Integer(), nullable=False))
    op.add_column('flats', sa.Column('tenant_name', sa.String(length=120), nullable=True))
    op.drop_index(op.f('ix_flats_label'), table_name='flats')
    op.drop_column('flats', 'label')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flats', sa.Column('label', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_flats_label'), 'flats', ['label'], unique=True)
    op.drop_column('flats', 'tenant_name')
    op.drop_column('flats', 'number')
    op.drop_column('flats', 'floor')
    # ### end Alembic commands ###
