"""init

Revision ID: cb58d4c75949
Revises: 3764a5d5e161
Create Date: 2026-01-28 17:03:58.014620

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cb58d4c75949'
down_revision = '3764a5d5e161'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flats', sa.Column('label', sa.String(length=64), nullable=False))
    op.add_column('flats', sa.Column('name', sa.String(), nullable=False))
    op.create_index(op.f('ix_flats_label'), 'flats', ['label'], unique=True)
    op.drop_column('flats', 'tenant_name')
    op.drop_column('flats', 'floor')
    op.drop_column('flats', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flats', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('flats', sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('flats', sa.Column('tenant_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_flats_label'), table_name='flats')
    op.drop_column('flats', 'name')
    op.drop_column('flats', 'label')
    # ### end Alembic commands ###
